import { i } from '@instantdb/react';

const _schema = i.schema({
  entities: {
    users: i.entity({
      email: i.string().unique().indexed(),
      passwordHash: i.string(),
      firstName: i.string(),
      lastName: i.string(),
      role: i.string().indexed(),
      departmentId: i.string().optional().indexed(),
      googleId: i.string().optional().unique(),
      googleRefreshToken: i.string().optional(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
    refreshTokens: i.entity({
      userId: i.string().indexed(),
      tokenHash: i.string().unique().indexed(),
      expiresAt: i.string().indexed(),
      revokedAt: i.string().optional().indexed(),
      replacedByTokenId: i.string().optional(),
      createdAt: i.string().indexed(),
    }),
    customers: i.entity({
      companyName: i.string().indexed(),
      billingAddress: i.string().optional(),
      phone: i.string().optional(),
      email: i.string().optional().indexed(),
      status: i.string().indexed(),
      contacts: i.json().optional(),
      notes: i.json().optional(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
    projects: i.entity({
      customerId: i.string().optional().indexed(),
      projectName: i.string().indexed(),
      description: i.string().optional(),
      status: i.string().indexed(),
      priority: i.string().indexed(),
      dueDate: i.string().optional().indexed(),
      assignedTo: i.string().optional().indexed(),
      driveFolderId: i.string().optional().indexed(),
      driveFolderUrl: i.string().optional(),
      driveFolderName: i.string().optional(),
      milestones: i.json().optional(),
      createdBy: i.string().indexed(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
    tasks: i.entity({
      projectId: i.string().optional().indexed(),
      assignedTo: i.string().optional().indexed(),
      title: i.string().indexed(),
      description: i.string().optional(),
      status: i.string().indexed(),
      priority: i.string().indexed(),
      dueDate: i.string().optional().indexed(),
      estimatedHours: i.number().optional(),
      actualHours: i.number().optional(),
      comments: i.json().optional(),
      createdBy: i.string().indexed(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
    documents: i.entity({
      projectId: i.string().optional().indexed(),
      fileName: i.string().indexed(),
      fileType: i.string().indexed(),
      mimeType: i.string().optional(),
      fileSize: i.number(),
      storagePath: i.string(),
      storageProvider: i.string().indexed(),
      revision: i.number(),
      status: i.string().indexed(),
      lockedBy: i.string().optional(),
      uploadedBy: i.string().indexed(),
      driveFileId: i.string().optional().indexed(),
      driveViewUrl: i.string().optional(),
      lastSyncError: i.string().optional(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
    timeEntries: i.entity({
      userId: i.string().indexed(),
      projectId: i.string().optional().indexed(),
      taskId: i.string().optional().indexed(),
      description: i.string().optional(),
      hours: i.number(),
      billable: i.boolean().indexed(),
      entryDate: i.string().indexed(),
      status: i.string().indexed(),
      startedAt: i.string().optional(),
      endedAt: i.string().optional(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
    quotes: i.entity({
      customerId: i.string().optional().indexed(),
      projectId: i.string().optional().indexed(),
      title: i.string().indexed(),
      status: i.string().indexed(),
      lineItems: i.json(),
      subtotal: i.number(),
      taxRate: i.number(),
      taxTotal: i.number(),
      total: i.number(),
      converted: i.boolean().indexed(),
      convertedInvoiceId: i.string().optional(),
      createdBy: i.string().indexed(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
    invoices: i.entity({
      customerId: i.string().optional().indexed(),
      projectId: i.string().optional().indexed(),
      quoteId: i.string().optional().indexed(),
      invoiceNumber: i.string().unique().indexed(),
      status: i.string().indexed(),
      issueDate: i.string().indexed(),
      lineItems: i.json(),
      subtotal: i.number(),
      taxRate: i.number(),
      taxAmount: i.number(),
      discountAmount: i.number(),
      total: i.number(),
      dueDate: i.string().optional().indexed(),
      paidAt: i.string().optional(),
      deletedAt: i.string().optional().indexed(),
      auditLog: i.json().optional(),
      createdBy: i.string().indexed(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
    notifications: i.entity({
      userId: i.string().indexed(),
      type: i.string().indexed(),
      title: i.string(),
      message: i.string(),
      readAt: i.string().optional().indexed(),
      link: i.string().optional(),
      emailQueued: i.boolean().indexed(),
      createdAt: i.string().indexed(),
    }),
    notificationPreferences: i.entity({
      userId: i.string().unique().indexed(),
      inApp: i.boolean(),
      email: i.boolean(),
      assignmentAlerts: i.boolean(),
      deadlineReminders: i.boolean(),
      mentionAlerts: i.boolean(),
    }),
    emailQueue: i.entity({
      notificationId: i.string().indexed(),
      userId: i.string().indexed(),
      status: i.string().indexed(),
      attempts: i.number(),
      lastError: i.string().optional(),
      sentAt: i.string().optional(),
      createdAt: i.string().indexed(),
      updatedAt: i.string(),
    }),
  },
});

type _AppSchema = typeof _schema;
interface AppSchema extends _AppSchema {}

const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
