export const instantDbSchema = {
  invoices: {
    id: 'uuid',
    invoiceNumber: { type: 'string', unique: true },
    customerId: { type: 'uuid', indexed: true },
    projectId: { type: 'uuid', optional: true },
    quoteId: { type: 'uuid', optional: true },
    status: 'draft | sent | paid | overdue | void',
    issueDate: 'date',
    dueDate: { type: 'date', optional: true },
    subtotal: 'number',
    taxRate: 'number',
    taxAmount: 'number',
    discountAmount: 'number',
    total: 'number',
    createdBy: 'uuid',
    createdAt: 'datetime',
    updatedAt: 'datetime',
    deletedAt: { type: 'datetime', optional: true },
  },
  invoiceLineItems: {
    id: 'uuid',
    invoiceId: 'uuid',
    description: 'string',
    quantity: 'number',
    unitPrice: 'number',
    total: 'number',
  },
  invoiceAuditEvents: {
    id: 'uuid',
    invoiceId: 'uuid',
    userId: 'uuid',
    action: 'string',
    timestamp: 'datetime',
  },
};
