export const currency = (value: number) => `$${value.toFixed(2)}`;

export const baseDocumentLines = (heading: string, rows: string[]) => [
  'ArchTrack',
  'Drafting and design operations',
  '',
  heading,
  '',
  ...rows,
  '',
  'Generated by ArchTrack. Email delivery can attach this export.',
];
